except-interface=lo
log-dhcp

# VLAN 130 — WiFi Invitados / Clientes  (/24, 130 hosts)
dhcp-range=set:vlan130,10.2.0.2,10.2.0.254,255.255.255.0,12h
dhcp-option=tag:vlan130,option:router,10.2.0.1
dhcp-option=tag:vlan130,option:dns-server,8.8.8.8

# VLAN 140 — Cajas / Checkout  (/27, 25 hosts)
dhcp-range=set:vlan140,10.2.1.2,10.2.1.30,255.255.255.224,12h
dhcp-option=tag:vlan140,option:router,10.2.1.1
dhcp-option=tag:vlan140,option:dns-server,8.8.8.8

# VLAN 40 — Oficina Administrativa  (/29, 3 hosts)
dhcp-range=set:vlan40,10.2.1.34,10.2.1.38,255.255.255.248,12h
dhcp-option=tag:vlan40,option:router,10.2.1.33
dhcp-option=tag:vlan40,option:dns-server,8.8.8.8

# VLAN 30 — Security  (/29, 3 hosts)
dhcp-range=set:vlan30,10.2.1.42,10.2.1.46,255.255.255.248,12h
dhcp-option=tag:vlan30,option:router,10.2.1.41
dhcp-option=tag:vlan30,option:dns-server,8.8.8.8

# VLAN 100 — Cámaras  (/25, 62 hosts)
dhcp-range=set:vlan100,10.2.1.50,10.2.1.110,255.255.255.128,12h
dhcp-option=tag:vlan100,option:router,10.2.1.49
dhcp-option=tag:vlan100,option:dns-server,8.8.8.8

# VLAN 110 — Impresoras  (/28, 9 hosts)
dhcp-range=set:vlan110,10.2.1.114,10.2.1.126,255.255.255.240,12h
dhcp-option=tag:vlan110,option:router,10.2.1.113
dhcp-option=tag:vlan110,option:dns-server,8.8.8.8

# VLAN 120 — Teléfonos  (/29, 6 hosts)
dhcp-range=set:vlan120,10.2.1.130,10.2.1.134,255.255.255.248,12h
dhcp-option=tag:vlan120,option:router,10.2.1.129
dhcp-option=tag:vlan120,option:dns-server,8.8.8.8
